### ISSUE TITLE
[Feature] add possibility to just point :story/:feature as independent param to test suite

### ISSUE THREAD

**Issue by d-konovalov** [allure-framework/allure-rspec#39]
I've faced that i write something like this:

```ruby
describe 'Some feature', feature: 'Some feature' do
  describe 'Some story', story: 'Some story' do
    it 'does smth'
  end
  describe 'Some another story', story: 'Some another story' do
    it 'does smth other'
  end
end
```

If we just could to do something like this:

```ruby
describe 'Some feature', :feature do
  describe 'Some story', :story do
    it 'does smth'
  end
end
```
we would have more clear and readable code. In this case you could to get value for this from the description of example_group. Of course we need to make current behavior available as well in case of we we have different values here
What you think?

**Comment by smecsia** [comment]
@d-konovalov Sorry for my absence in this ticket. The fact is that I've merged this PR into the new version...
As for your feedback... I'm not sure I understand you correctly. Metadata values in RSpec are inheritable by default and this is actually the right behavior, because allure builder considers that testcases, that have `story` label must also have the `feature` label. The fact is that `:story` is a sub label for `:feature`. Current implementation allows to build  the "Behaviors" tab of allure report rightly.
Why do you want to detect the source of  the label?

**Comment by d-konovalov** [comment]
@smecsia Hi, need more time to investigate. I don't remember actually. I'll write feedback later

**Comment by smecsia** [comment]
Outdated.
